# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /fsf/tylerp16/myECEN330/ecen330

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /fsf/tylerp16/myECEN330/ecen330

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /fsf/tylerp16/myECEN330/ecen330/CMakeFiles /fsf/tylerp16/myECEN330/ecen330//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /fsf/tylerp16/myECEN330/ecen330/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BOOT.bin

# Build rule for target.
BOOT.bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BOOT.bin
.PHONY : BOOT.bin

# fast build rule for target.
BOOT.bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BOOT.bin.dir/build.make CMakeFiles/BOOT.bin.dir/build
.PHONY : BOOT.bin/fast

#=============================================================================
# Target rules for targets named lab1.elf

# Build rule for target.
lab1.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab1.elf
.PHONY : lab1.elf

# fast build rule for target.
lab1.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab1_helloworld/CMakeFiles/lab1.elf.dir/build.make lab1_helloworld/CMakeFiles/lab1.elf.dir/build
.PHONY : lab1.elf/fast

#=============================================================================
# Target rules for targets named lab2.elf

# Build rule for target.
lab2.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab2.elf
.PHONY : lab2.elf

# fast build rule for target.
lab2.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab2_gpio/CMakeFiles/lab2.elf.dir/build.make lab2_gpio/CMakeFiles/lab2.elf.dir/build
.PHONY : lab2.elf/fast

#=============================================================================
# Target rules for targets named lab3_m1.elf

# Build rule for target.
lab3_m1.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab3_m1.elf
.PHONY : lab3_m1.elf

# fast build rule for target.
lab3_m1.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab3_timer/CMakeFiles/lab3_m1.elf.dir/build.make lab3_timer/CMakeFiles/lab3_m1.elf.dir/build
.PHONY : lab3_m1.elf/fast

#=============================================================================
# Target rules for targets named lab3_m2.elf

# Build rule for target.
lab3_m2.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab3_m2.elf
.PHONY : lab3_m2.elf

# fast build rule for target.
lab3_m2.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab3_timer/CMakeFiles/lab3_m2.elf.dir/build.make lab3_timer/CMakeFiles/lab3_m2.elf.dir/build
.PHONY : lab3_m2.elf/fast

#=============================================================================
# Target rules for targets named lab4.elf

# Build rule for target.
lab4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab4.elf
.PHONY : lab4.elf

# fast build rule for target.
lab4.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab4_interrupts/CMakeFiles/lab4.elf.dir/build.make lab4_interrupts/CMakeFiles/lab4.elf.dir/build
.PHONY : lab4.elf/fast

#=============================================================================
# Target rules for targets named lab5.elf

# Build rule for target.
lab5.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab5.elf
.PHONY : lab5.elf

# fast build rule for target.
lab5.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab5_touchscreen/CMakeFiles/lab5.elf.dir/build.make lab5_touchscreen/CMakeFiles/lab5.elf.dir/build
.PHONY : lab5.elf/fast

#=============================================================================
# Target rules for targets named lab6.elf

# Build rule for target.
lab6.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab6.elf
.PHONY : lab6.elf

# fast build rule for target.
lab6.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab6_clock/CMakeFiles/lab6.elf.dir/build.make lab6_clock/CMakeFiles/lab6.elf.dir/build
.PHONY : lab6.elf/fast

#=============================================================================
# Target rules for targets named lab7_m1.elf

# Build rule for target.
lab7_m1.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab7_m1.elf
.PHONY : lab7_m1.elf

# fast build rule for target.
lab7_m1.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab7_tictactoe/CMakeFiles/lab7_m1.elf.dir/build.make lab7_tictactoe/CMakeFiles/lab7_m1.elf.dir/build
.PHONY : lab7_m1.elf/fast

#=============================================================================
# Target rules for targets named lab7_m2.elf

# Build rule for target.
lab7_m2.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab7_m2.elf
.PHONY : lab7_m2.elf

# fast build rule for target.
lab7_m2.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab7_tictactoe/CMakeFiles/lab7_m2.elf.dir/build.make lab7_tictactoe/CMakeFiles/lab7_m2.elf.dir/build
.PHONY : lab7_m2.elf/fast

#=============================================================================
# Target rules for targets named lab8_m1.elf

# Build rule for target.
lab8_m1.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab8_m1.elf
.PHONY : lab8_m1.elf

# fast build rule for target.
lab8_m1.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab8_missilecommand/CMakeFiles/lab8_m1.elf.dir/build.make lab8_missilecommand/CMakeFiles/lab8_m1.elf.dir/build
.PHONY : lab8_m1.elf/fast

#=============================================================================
# Target rules for targets named lab8_m2.elf

# Build rule for target.
lab8_m2.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab8_m2.elf
.PHONY : lab8_m2.elf

# fast build rule for target.
lab8_m2.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab8_missilecommand/CMakeFiles/lab8_m2.elf.dir/build.make lab8_missilecommand/CMakeFiles/lab8_m2.elf.dir/build
.PHONY : lab8_m2.elf/fast

#=============================================================================
# Target rules for targets named lab8_m3.elf

# Build rule for target.
lab8_m3.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab8_m3.elf
.PHONY : lab8_m3.elf

# fast build rule for target.
lab8_m3.elf/fast:
	$(MAKE) $(MAKESILENT) -f lab8_missilecommand/CMakeFiles/lab8_m3.elf.dir/build.make lab8_missilecommand/CMakeFiles/lab8_m3.elf.dir/build
.PHONY : lab8_m3.elf/fast

#=============================================================================
# Target rules for targets named buttons_switches

# Build rule for target.
buttons_switches: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 buttons_switches
.PHONY : buttons_switches

# fast build rule for target.
buttons_switches/fast:
	$(MAKE) $(MAKESILENT) -f drivers/CMakeFiles/buttons_switches.dir/build.make drivers/CMakeFiles/buttons_switches.dir/build
.PHONY : buttons_switches/fast

#=============================================================================
# Target rules for targets named intervalTimer

# Build rule for target.
intervalTimer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intervalTimer
.PHONY : intervalTimer

# fast build rule for target.
intervalTimer/fast:
	$(MAKE) $(MAKESILENT) -f drivers/CMakeFiles/intervalTimer.dir/build.make drivers/CMakeFiles/intervalTimer.dir/build
.PHONY : intervalTimer/fast

#=============================================================================
# Target rules for targets named interrupts

# Build rule for target.
interrupts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interrupts
.PHONY : interrupts

# fast build rule for target.
interrupts/fast:
	$(MAKE) $(MAKESILENT) -f drivers/CMakeFiles/interrupts.dir/build.make drivers/CMakeFiles/interrupts.dir/build
.PHONY : interrupts/fast

#=============================================================================
# Target rules for targets named touchscreen

# Build rule for target.
touchscreen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 touchscreen
.PHONY : touchscreen

# fast build rule for target.
touchscreen/fast:
	$(MAKE) $(MAKESILENT) -f drivers/CMakeFiles/touchscreen.dir/build.make drivers/CMakeFiles/touchscreen.dir/build
.PHONY : touchscreen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BOOT.bin"
	@echo "... buttons_switches"
	@echo "... interrupts"
	@echo "... intervalTimer"
	@echo "... lab1.elf"
	@echo "... lab2.elf"
	@echo "... lab3_m1.elf"
	@echo "... lab3_m2.elf"
	@echo "... lab4.elf"
	@echo "... lab5.elf"
	@echo "... lab6.elf"
	@echo "... lab7_m1.elf"
	@echo "... lab7_m2.elf"
	@echo "... lab8_m1.elf"
	@echo "... lab8_m2.elf"
	@echo "... lab8_m3.elf"
	@echo "... touchscreen"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

