#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_TOUCHSCREEN_TIMER_PERIOD 10.0E-3
#define CONFIG_GAME_TIMER_PERIOD 45.0E-3

#define CONFIG_MAX_LASERS 7

#define CONFIG_COLOR_LASER DISPLAY_RED

#define CONFIG_BACKGROUND_COLOR DISPLAY_BLACK

#endif /* CONFIG_H */